### ISSUE TITLE
Update travis.yml to latest odk version

### ISSUE THREAD

**Issue by cmungall** [Planteome/plant-experimental-conditions-ontology#109]

**Comment by marieALaporte** [comment]
I'll work on that then and see if that fixes the problem

**Comment by marieALaporte** [comment]
@cmungall if I run make test in Docker, it crashes on running the extract command for NCBITaxon. If I use robot outside Docker, I don't have any problem.

The errors I am getting after playing with the Docker preferences:
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded (Memory set up to 6 GiB)
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space (Memory set up to 8 GiB)
I am still waiting to see what happens for memory set up to 10 GiB. It's been 20 minutes and it's still running.

I know that I don't have the greatest laptop, but the difference between using Docker and not using Docker is huge. What are the recommended settings for Docker? I guess that I won't be the only one running into those issues.

**Comment by marieALaporte** [comment]
update: java.lang.OutOfMemoryError: Java heap space even when memory is set up to 10 GiB
