### ISSUE TITLE
new term: potassium fertilizer exposure

### ISSUE THREAD

**Issue by richardostler** [Planteome/plant-experimental-conditions-ontology#112]
Can the following be added under [chemical fertilizer exposure](http://purl.obolibrary.org/obo/PECO_0007086):
**Preferred term:** potassium fertilizer exposure
Definition: Treatment involving the use of potassium fertilizer and its components as supplements to study various types of responses.

**Preferred term:** potassium chloride exposure
alternative term: muriate of potash exposure
definition: Treatment involving the use of potassium chloride supplement to study various types of responses.
subclass of: potassium fertilizer exposure

thanks

**Comment by cooperl09** [comment]
Hi Richard, Here are the terms you requested.
They will be available on our development browser (http://dev.planteome.org/amigo/dd_browse) on Friday Oct. 19, 2018.
[Term]
id: PECO:0001064
name: potassium fertilizer exposure
def: "A chemical fertilizer exposure (PECO:0007086) involving the use of potassium fertilizer as a supplement to study plant responses." [PECO:cooperl]
xref: PECO_GIT:112
is_a: PECO:0007086 ! chemical fertilizer exposure
created_by: Laurel_Cooper
creation_date: 2018-10-18T17:40:45Z

[Term]
id: PECO:0001065
name: potassium chloride exposure
def: "A potassium fertilizer exposure (PECO:0001064) involving the use of potassium chloride fertilizer as a supplement to study plant responses." [PECO:cooperl]
synonym: "muriate of potash exposure (related)" RELATED []
xref: PECO_GIT:112
is_a: PECO:0001064 ! potassium fertilizer exposure
created_by: Laurel_Cooper
creation_date: 2018-10-18T17:51:54Z

**Comment by richardostler** [comment]
Thanks Laurel
