### ISSUE TITLE
new term: nematicide exposure

### ISSUE THREAD

**Issue by richardostler** [Planteome/plant-experimental-conditions-ontology#113]
Please can the term nematicide exposure be added as a subclass of [pesticide exposure](http://purl.obolibrary.org/obo/PECO_0007167). 
Definition: A pesticide exposure (PECO:0007167) involving the application of a nematicde; a chemical entity or mixture of chemical entities.

thanks

**Comment by cooperl09** [comment]
Hi Richard, Here is the term you requested.
It will be available on our development browser (http://dev.planteome.org/amigo/dd_browse) on Friday Oct. 19, 2018.
[Term]
id: PECO:0001066
name: nematicide exposure
def: "A pesticide exposure (PECO:0007167) involving the application of a nematicide; a chemical entity or mixture of chemical entities to kill plant-parasitic nematodes." []
xref: PECO_GIT:113
is_a: PECO:0007167 ! pesticide exposure
created_by: Laurel_Cooper
creation_date: 2018-10-18T18:51:16Z

**Comment by richardostler** [comment]
Thanks Laurel
