### ISSUE TITLE
NTR: castor meal exposure

### ISSUE THREAD

**Issue by richardostler** [Planteome/plant-experimental-conditions-ontology#115]
Can **castor meal exposure** be added as a subclass of [natural fertilizer exposure](http://purl.obolibrary.org/obo/PECO_0007087)

**Comment by cooperl09** [comment]
Yes.  It would be helpful if you could propose a definition.

**Comment by richardostler** [comment]
How is this:

Treatment involving the use of castor meal as an organic fertilizer. Castor meal is a by product of castor oil production and has a high nitrogen content.

**Comment by cooperl09** [comment]
New term created:
castor meal exposure (PECO:0001067): A natural fertilizer exposure (PECO:0007087) which is the application of castor meal.  
Comment: Castor meal is a by-product of castor oil production from seeds of the Castor (Ricinus communis) plant and has a high nitrogen content.
synonym: castor meal treatment (exact)

**Comment by cooperl09** [comment]
If you have a literature reference such as a PubMed ID, I can add it.

**Comment by richardostler** [comment]
The best I can find is this article... https://doi.org/10.1016/j.indcrop.2010.11.008
