### ISSUE TITLE
NTR: rapeseed meal exposure

### ISSUE THREAD

**Issue by richardostler** [Planteome/plant-experimental-conditions-ontology#117]
Can **rape cake** with synonym **rapeseed cake** be added as a subclass of [natural fertilizer exposure](http://purl.obolibrary.org/obo/PECO_0007087)

**Comment by richardostler** [comment]
On reflection, can rapeseed cake be the preferred term and _rape cake_ and _rapeseed meal_ added as synonyms.

*Defnition:
Treatment involving the use of rapeseed meal as an organic fertilizer. Rapeseed meal is a by product of rapeseed oil production and has a high protein content.

**Comment by cooperl09** [comment]
Prefer the name "rapeseed meal exposure" as it better reflects the definition.  

Proposed name and def'n: 
id: PECO:0001068
name: rapeseed meal exposure
def: "A natural fertilizer exposure (PECO:0007087) which is the application of rapeseed meal." []
comment: Rapeseed meal is a by-product of oil production from seeds of the Rapeseed (Brassica napus L.) plant and has a high protein content.
synonym: "rape cake exposure (narrow)" NARROW []
synonym: "rapeseed cake exposure (narrow)" NARROW []

**Comment by richardostler** [comment]
Thanks, agree with adding exposure and the improved definition.
