### ISSUE TITLE
NTR: Rhizobium leguminosarum exposure

### ISSUE THREAD

**Issue by richardostler** [Planteome/plant-experimental-conditions-ontology#120]
Please can you add a new term for Rhizobium leguminosarum exposure
Name: Rhizobium leguminosarum exposure
definition: A treatment involving exposure of the plant, typically as a [seed dressing],(http://purl.obolibrary.org/obo/AGRO_00000051) to the mutualistic symbiont Rhizobium leguminosarum. It has the ability to fix free nitrogen from air. {xref="Wikipedia:Rhizobium_leguminosarum"}
subclass of: http://purl.obolibrary.org/obo/PECO_0007246 - but I note, all other concepts here seem to be pathogens rather than have a commensal or symbiotic relationship with the plant - presumably this doesn't matter?

**Comment by cooperl09** [comment]
New term has been added:
id: PECO:0001072
name: Rhizobium leguminosarum exposure
def: "A bacterial plant exposure (PECO:0007246) involving exposure of the plant to Rhizobium leguminosarum." [NCBITaxon:384, PECO:cooperl]
comment: Rhizobium leguminosarum is a mutualistic symbiont which has the has the ability to fix free nitrogen from the air.  It is typically applied as a as a seed dressing.
xref: PECO_GIT:120
is_a: PECO:0007246 ! bacterial plant exposure

The new term will be available on our development browser tomorrow: https://dev.planteome.org/amigo
