### ISSUE TITLE
NTR Zymoseptoria tritici exposure

### ISSUE THREAD

**Issue by richardostler** [Planteome/plant-experimental-conditions-ontology#123]
Hi PECO team, 

Please can you add the following under Ascomycota exposure (http://purl.obolibrary.org/obo/PECO_0007107)
 
Name: Zymoseptoria tritici exposure
definition: A treatment involving exposure of a plant to the pathogen Zymoseptoria tritici (http://purl.obolibrary.org/obo/NCBITaxon_1047171). It is a causal agent of leaf blotch in wheat

thanks
Richard

**Comment by cooperl09** [comment]
Hi @richardostler 
Term has been created: 
id: PECO:0001071
name: Zymoseptoria tritici exposure
def: "An Ascomycota exposure (PECO:0007107) which is the exposure of a plant the to the pathogen Zymoseptoria tritici." [NCBITaxon:1047171, PECO:cooperl]
comment: Zymoseptoria tritici (NCBITaxon_1047171) is a causal agent of leaf blotch in wheat.
xref: PECO_GIT:123
is_a: PECO:0007107 ! Ascomycota exposure

The new term will be available on our development browser tomorrow: https://dev.planteome.org/amigo
