### ISSUE TITLE
Add aeroponic term

### ISSUE THREAD

**Issue by baptisteImbert** [Planteome/plant-experimental-conditions-ontology#128]
Hi,

There is currently a term for hydroponic plant culture media exposure (PECO_0007067), but none to my knowledge for aeroponic plant culture media exposure.
I guess this term would have PECO_0007147 as parent term as well.

Thank you for you work!

Baptiste

**Comment by cooperl09** [comment]
Dear Baptiste, 
I have created the requested term: 
id: PECO:0001073
name: aeroponic plant growth media exposure
def: "A plant growth medium exposure (PECO:0007147) involving the growth of plants in an air and/or a mist environment, without the use of soil or an aggregate medium." [PECO:cooperl, Wikipedia: Aeroponics]
xref: PECO_GIT:128
is_a: PECO:0007147 ! plant growth medium exposure
created_by: http://orcid.org/0000-0002-6379-8932
creation_date: 2022-09-20T23:04:36Z

It will be available on our development browser within 24 hours

Best, Laurel
