### ISSUE TITLE
Update to  Plant Environment Ontology on identifiers.org

### ISSUE THREAD

**Issue by renatocjn** [Planteome/plant-experimental-conditions-ontology#133]
Hello,

It was recently brought to our attention here at identifers.org that we have an issue with our entry for the plant environment ontology. Seems like the issue is due to the person that registered trying to answer to the EO and to the PEO prefixes with only one namespace. It seems like EO was replaced with PECO according to [this](https://browser.planteome.org/amigo/term/EO:0007359), was this also done to the PEO prefix?

Any clarification would be greatly appreciated.

**Comment by cooperl09** [comment]
The Plant Environment Ontology (EO) was deprecated and replaced with the Plant Experimental Conditions Ontology (PECO).  We have never had an ontology with the PEO prefix, not can I locate one at OBO Foundry or EBI-OLS. 
I am not familiar with your system at identifiers.org.  Could you please provide an example of where this is used?

**Comment by renatocjn** [comment]
Hi, I'm very sorry for forgetting this issue open. I will close it now.
We will mark EO as deprecated on our registry if this is not available anymore.

Our system provides a registry of data collections and a resolver to the data in them. Our URLs and Compact identifiers can be used as permanent identifiers when referencing data in the collections. The PEO prefix because our current regex pattern allows it.
