### ISSUE TITLE
New Term Request: Knop's solution

### ISSUE THREAD

**Issue by kdumschott** [Planteome/plant-experimental-conditions-ontology#134]
##Term label

Knop's solution

##Synonym

Knop medium, Knop ME

##Textual definition

A nutrient solution used in growth experiments with higher plants and containing definite proportions of calcium nitrate, potassium nitrate, magnesium sulfate, monobasic potassium phosphate, and potassium chloride dissolved in water (Definition from https://www.merriam-webster.com/dictionary/Knop%27s%20solution)

##Parent term

Could potentially fit under micronutrient exposure (PECO:0007239) or fertilizer exposure (PECO:0007085), but could also fit under a new parent term such as nutrient solution, which could contain other child terms relevant to plant experiments, such as Hoagland solutions, which are commonly used in growth experiments involving plants like tomato and bell pepper.

**Comment by cooperl09** [comment]
Created a new term: 
Knop's solution exposure  PECO:0001074 
def: "A hydroponic plant culture media exposure (PECO:0007067) which is an exposure to Knop's solution during growth." [PECO:cooperl]
comment: Knop's solution is a nutrient solution used in growth experiments with higher plants and containing definite proportions of calcium nitrate, potassium nitrate, magnesium sulfate, monobasic potassium phosphate, and potassium chloride dissolved in water (https://www.merriam-webster.com/dictionary).
synonym: "Knop ME (related)" RELATED []
synonym: "Knop medium (related)" RELATED []

It is a child term of hydroponic plant culture media exposure (PECO:0007067) and sibling to the existing id: PECO:0007405  Hoagland solution exposure
