### ISSUE TITLE
PECO not being processed by OLS

### ISSUE THREAD

**Issue by haideriqbal** [Planteome/plant-experimental-conditions-ontology#138]
One of the PECO imports is not in RDF format hence the PECO ontology can't be processed by the OLS. The import in question is the following:
`<owl:imports rdf:resource="http://purl.obolibrary.org/obo/peco/patterns/exposure-chebi_pattern.owl"/>`

As a temporary fix (https://github.com/EBISPOT/ols4/pull/658) we are loading an old version of PECO for now in OLS which doesn't have this import. It would be great if this import issue could be resolved so that the latest version of PECO can be processed by OLS.

**Comment by marieALaporte** [comment]
it should be fixed now. Let me know if you are still facing any issue

**Comment by haideriqbal** [comment]
Thanks for the quick fix @marieALaporte! tested it and it works now.
