### ISSUE TITLE
seasonal environment (EO:0007027) and child terms

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-experimental-conditions-ontology#83]
Moved to be is_a plant treatment from plant growth environment (obsoleted).

seasonal environment ([EO:0007027](http://purl.obolibrary.org/obo/EO_0007027))
A plant treatment ([EO:0001001](http://purl.obolibrary.org/obo/EO_0001001)) involving an exposure to a given conditions of regional seasons. 

Reported by: cooperl09

Original Ticket: [obo/plant-environment-ontology-eo/84](https://sourceforge.net/p/obo/plant-environment-ontology-eo/84)

**Comment by cmungall** [comment]
Closing as it looks this was done.

For axiomatizing, see: https://github.com/Planteome/plant-environment-ontology/issues/97
