### ISSUE TITLE
EO term for "untreated Control" in osmotic stress RNA seq expt

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-experimental-conditions-ontology#88]
From Sunita Kumari:
Sunita: What EO term do you use for control treatment?
I mean e.g there are two samples, one has ABA treatment other is simple water treatment (no ABA), so will be used as control
for ABA: [EO:0007105](http://purl.obolibrary.org/obo/EO_0007105)

RNA-seq data from one of our paper http://www.ncbi.nlm.nih.gov/pubmed/22008187
We need metadata annotation for KBase, so there were ABA, PEG treatments and for control we used water and NaOH.

Reported by: cooperl09

Original Ticket: [obo/plant-environment-ontology-eo/89](https://sourceforge.net/p/obo/plant-environment-ontology-eo/89)

**Comment by cooperl09** [comment]
Added new term: control treatment (EO:0001062): A plant treatment (EO:0001001) used as a reference to compare the effects of one or more treatment factors in a study.
Is_a: plant treatment (EO:0001001)

Added comment: A control treatment may involve the application of inert factors such as water in an experiment, or no treatment at all.

**Comment by cooperl09** [comment]
I could see some rationales for actually making this term a sibling of plant treatment, rather than is_a plant treatment.
